contentdensity/contentdensity/urls.py
from django.conf import settings 
from django.conf.urls import url, include 
from django.conf.urls.static import static 
from django.contrib import admin
from django.views.generic import RedirectView 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^textifai/', include('textifai.urls')), 
    url(r'^$', RedirectView.as_view(url='/textifai/', permanent=True)), 
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

contentdensity/textifai/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^textinput/$', views.textinput, name='textinput'),
    url(r'^featureoutput/(?P<pk>[-\w]+$)', views.featureoutput, name='featureoutput'),
    url(r'^account', views.account, name='account'),
    url(r'^general-insights$', views.general_insights, name='general-insights'),
    url(r'^texts$', views.allTexts, name='text-list'),
    url(r'^searchresults/(?P<query>.*$)', views.searchresults, name='searchresults'),
]

contentdensity/textifai/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
import datetime

# Create your models here.

class Text(models.Model):
    """
    Model representing text from user input.
    """
    m_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular text.")
    title = models.CharField(max_length=40,  blank=True, help_text="Enter a title for your entry")
    content = models.TextField(help_text="Enter text here")
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    mature_content = models.BooleanField()

    class Meta:
        ordering = ["-time_created"]

    def get_absolute_url(self):
        """
        Returns the url to access a particular Text instance.
        """
        return reverse('featureoutput', args=[str(self.m_id)])

    def __str__(self):
        """
        String for representing the Text object.
        """
        return self.content


class Insight(models.Model):
    """
    Model representing an insight associated with text.
    """
    m_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular insight.")
    tone = models.CharField(max_length=100)
    probability = models.FloatField()
    text = models.ForeignKey(Text)
    user = models.ForeignKey(User)

    def get_absolute_url(self):
        """
        Returns the url to access a particular Insight instance.
        """
        return reverse('insight-detail', args=[str(self.m_id)])

    def __str__(self):
        """
        String for representing the Insight object.
        """
        return self.tone

class GrammaticalInsight(models.Model):
    """
    Model representing a grammatical insight associated with text.
    """
    ADJECTIVE = 'ADJ'
    ADPOSITION = 'ADP'
    ADVERB = 'ADV'
    CONJUNCTION = 'CONJ'
    DETERMINER = 'DET'
    NOUN = 'NOUN'
    NUMERICAL = 'NUM'
    PARTICLE = 'PRT'
    PRONOUN = 'PRO'
    VERB = 'VERB'
    PUNCTUATION = '.'
    OTHER = 'X'

    PARTS_OF_SPEECH = (
        (ADJECTIVE, 'Adjective'),
        (ADPOSITION, 'Adposition'),
        (ADVERB, 'Adverb'),
        (CONJUNCTION, 'Conjunection'),
        (DETERMINER, 'Determiner'),
        (NOUN, 'Noun'),
        (NUMERICAL, 'Numerical'),
        (PARTICLE, 'Particle'),
        (PRONOUN, 'Pronoun'),
        (VERB, 'Verb'),
        (PUNCTUATION, 'Punctuation'),
        (OTHER, 'Other'),
    )

    m_id = models.UUIDField(primary_key=True, default=uuid.uuid4
                            , help_text="Unique ID for GrammaticalInsight.")
    user = models.ForeignKey(User)
    text = models.ForeignKey(Text)

    positivity = models.CharField(max_length=24)
    most_common_pos = models.CharField(max_length=4, choices=PARTS_OF_SPEECH)
    reading_level = models.CharField(max_length=100)
    reading_time = models.CharField(max_length=100)
    speaking_time = models.CharField(max_length=100)
    total_words = models.IntegerField()
    total_chars = models.IntegerField()
    total_sentences = models.IntegerField()
    most_common_word = models.CharField(max_length=100)
    average_word_length = models.IntegerField()
    word_reuse_percentage = models.FloatField(default=1)


    def get_absolute_url(self):
        """
        Returns the url to access a particular GrammaticalInsight instance.
        """
        return reverse('grammaticalinsight-detail', args=[str(self.m_id)])

    def __str__(self):
        """
        String for representing the GrammaticalInsight object.
        """
        return "positivity: {}, most_common_pos: {}, reading_level: {}, " \
               "reading_time: {}, speaking_time: {}, total_words: {}, " \
               "total_chars: {}, most_common_word: {}, average_word_length: {}" \
               "".format(self.positivity
                         , self.most_common_pos
                         , self.reading_level
                         , self.reading_time
                         , self.speaking_time
                         , self.total_words
                         , self.total_chars
                         , self.most_common_word
                         , self.average_word_length)

class Comment(models.Model):
    """
    Model representing a comment associated with text and a user.
    """
    m_id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular comment.")
    content = models.TextField(max_length=500)
    text = models.ForeignKey(Text)
    time_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    def get_absolute_url(self):
        """
        Returns the url to access a particular Comment instance.
        """
        return reverse('comment-detail', args=[str(self.m_id)])

    def __str__(self):
        """
        String for representing the Comment object.
        """
        return self.content

class GeneralInsight(models.Model):
    """
    Model representing a general insight
    """
    name = models.CharField(primary_key=True, max_length=127)
    value = models.CharField(max_length=127, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular GeneralInsight instance.
        """
        return reverse('gen-insight-detail', args=[str(self.m_id)])

    def __str__(self):
        """
        String for representing the GeneralInsight object.
        """
        return self.name

    def save(self, *args, **kwargs):
        self.full_clean()
        super(type(self), self).save(*args, **kwargs)

    def clean(self):
        self.name = self.name.strip()
        self.value = self.value.strip()

contentdensity/textifai/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class TextAnalysisForm(forms.Form):
    text_analysis_input = forms.CharField(widget=forms.Textarea)
    text_title = forms.CharField(max_length=40, required=False)

    def clean_text_analysis_input(self):
        data = self.cleaned_data['text_analysis_input']
        if not data:
            raise ValidationError(
                _('Invalid text - tried to submit empty input'))
        return data


class CommentInputForm(forms.Form):
    comment_input = forms.CharField()

    def clean_comment_input(self):
        data = self.cleaned_data['comment_input']
        if not data:
            raise ValidationError(
                _('Invalid comment - tried to submit an empty comment'))
        return data


class EditedTextForm(forms.Form):
    edited_text = forms.CharField()

    def clean_edited_text(self):
        data = self.cleaned_data['edited_text']
        return data


class FileUploadForm(forms.Form):
    file = forms.FileField()
    
    def clean_text_analysis_input(self):
        self.file.open(mode='rb') 
        data = self.file.readlines()
        self.file.close()
        if not data:
            raise ValidationError(
                _('Invalid text - tried to upload empty file'))
        return data


class SearchForm(forms.Form):
    search_input = forms.CharField()
    def clean_search_input(self):
        data = self.cleaned_data['search_input'].lower()
        return data

contentdensity/textifai/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count, Avg
from .models import User, Text, Insight, Comment, GeneralInsight, \
    GrammaticalInsight
from .modules import gic, textanalyzer
from .forms import *
import random


# Create your views here.

def index(request):
    """
    View function for the homepage of the site
    """
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['search_input']
            return HttpResponseRedirect(reverse('searchresults', args=(query,)))

    recent = Text.objects.all()[:4]
    return render(request, 'index.html', context={'recent': recent})

def _find_matches(query):
    return [text for text in Text.objects.all() if _text_contains_query(text, query)]

def _text_contains_query(text, query):
    return query in text.content.lower() or query in text.title.lower()

def searchresults(request, query): 
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['search_input']
            return HttpResponseRedirect(reverse('searchresults', args=(query,)))

    results = _find_matches(query)
    return render(request, 'searchresults.html', context={'results': results})

def _save_insights(insights, text, user):
    [Insight(tone=x[0], probability=x[1], text=text, user=user).save() for x in insights]

def _save_grammatical_insight(analysis, text, user):
    GrammaticalInsight(user=user
                       , text=text
                       , positivity=analysis.get_sentiment()
                       , most_common_pos=analysis.get_most_common_pos()
                       , reading_level=analysis.get_reading_level()
                       , reading_time=analysis.get_reading_time()
                       , speaking_time=analysis.get_speaking_time()
                       , total_words=analysis.get_total_words()
                       , total_chars=analysis.get_total_characters()
                       , most_common_word=analysis.get_most_common_word()
                       , average_word_length=analysis.get_average_word_length()
                       , total_sentences= analysis.get_num_sentences()
                       , word_reuse_percentage = analysis.get_word_reuse_percentage()
                      ).save()


def _save_text_analysis(user, analysis, title):
    text = Text(title=title, content=analysis.text, user=user, mature_content=False)
    text.save()

    _save_insights(analysis.get_insights(), text, user)
    _save_grammatical_insight(analysis, text, user)
    return text.m_id


def _edit_text_analysis(original_text, user, analysis):
    _delete_all_insights(original_text)

    original_text.content = analysis.text
    original_text.save()

    _save_insights(analysis.get_insights(), original_text, user)
    _save_grammatical_insight(analysis, original_text, user)


def _delete_all_insights(text):
    Insight.objects.filter(text=text).delete()
    GrammaticalInsight.objects.filter(text=text).delete()


@login_required
def textinput(request):
    """
    View function for the text input page of the site.
    """
    if request.method == 'POST':
        if len(request.FILES) != 0:
            form = FileUploadForm(request.POST)
            file = request.FILES['file']
            if form.is_valid():
                return _submit_text_file(form, file, request.user)
        else:
            form = TextAnalysisForm(request.POST)
            if form.is_valid():
                return _submit_text(form, request.user)

    return render(request, 'textinput.html', context={})

    
def _submit_text(form, user):
    text = form.cleaned_data['text_analysis_input']
    title = form.cleaned_data['text_title']
    text_analysis = textanalyzer.TextAnalyzer(text)
    m_id = _save_text_analysis(user, text_analysis, title)
    return HttpResponseRedirect(reverse('featureoutput', args=(m_id,)))


def _submit_comment(form, text, user):
    comment_text = form.cleaned_data['comment_input']
    Comment(content=comment_text, text=text, user=user).save()
    return HttpResponseRedirect(reverse('featureoutput', args=(text.m_id,)))


def _submit_edited_text(form, text, user):
    edited_text = form.cleaned_data['edited_text']
    text_analysis = textanalyzer.TextAnalyzer(edited_text)
    _edit_text_analysis(text, user, text_analysis)
    return HttpResponseRedirect(reverse('featureoutput', args=(text.m_id,)))

    
def _submit_text_file(form, file, user):
    file_text = form.cleaned_data['file_upload']
    text_analysis = textanalyzer.TextAnalyzer(file_text)
    m_id = _save_text_analysis(user, text_analysis)
    return HttpResponseRedirect(reverse('featureoutput', args=(m_id,)))

    
def _post_featureoutput(request, text): 
    if request.POST.get("new_submission_button"):
        return redirect('textinput')

    if request.POST.get("edit_submission_button"):
        form = EditedTextForm(request.POST)
        if form.is_valid():
            return _submit_edited_text(form, text, request.user)

    if request.POST.get("comment_input_button"):
        form = CommentInputForm(request.POST)
        if form.is_valid():
            return _submit_comment(form, text, request.user)

    return HttpResponseRedirect(reverse('featureoutput', args=(text.m_id,)))


def _render_featureoutput(request, text):
    context_dict = {
        'text': text,
        'author': text.user,
        'insights': Insight.objects.filter(text=text),
        'g_insights': GrammaticalInsight.objects.filter(text=text).first(),
        'comments': Comment.objects.filter(text=text),}
    return render(request, 'featureoutput.html', context=context_dict)


def featureoutput(request, pk):
    """
    View function for the feature output page of the site.
    """
    text = get_object_or_404(Text, pk=pk)
    return _post_featureoutput(request, text) if request.method == 'POST' else\
        _render_featureoutput(request, text)


@login_required
def account(request):
    """
    View function for user accounts.
    """
    if request.user.is_authenticated:
        texts = Text.objects.filter(user=request.user)[:3]
        comments = Comment.objects.filter(user=request.user)[:3]
        analytics = Insight.objects.filter(user=request.user).values('tone').annotate(Avg('probability')).order_by('-probability__avg')[:5]
    return render(
        request,
        "account.html",
        context={'user': request.user, 'texts': texts, 'comments': comments,
                 'analytics': analytics}
    )


def general_insights(request):
    """
    View function for the general insights page of the site.
    """
    if not hasattr(general_insights, 'has_run'):
        general_insights.has_run = 1
        for tone in set([ insight.tone for insight in Insight.objects.all()]):
            gic.add_general_insight('Average ' + tone,
                    gic._calc_global_insight_probability, tone)

    gic.calc_and_save_general_insights()
    insights = GeneralInsight.objects.order_by('?')
    true_personal_insights = dict()

    if request.user.is_authenticated:
        personal_insights = Insight.objects.filter(user=request.user,
                    text__isnull=False)

        true_personal_insights = dict()

        for tone in set([ insight.tone for insight in personal_insights ]):
            try:
                true_personal_insights[tone] = sum([ insight.probability
                        for insight in personal_insights
                        if insight.tone == tone ]) / len([ insight
                        for insight in personal_insights
                        if insight.tone == tone ])

            except ZeroDivisionError:
                continue

            true_personal_insights[tone] = "{:.0%}".format(
                    true_personal_insights[tone])

        true_personal_insights = list(true_personal_insights.items())
        random.shuffle(true_personal_insights)
    else:
        true_personal_insights = []

    return render(
        request,
        'general-insights.html',
        context={
            'insights': insights,
            'personal_insights': true_personal_insights[:4]
        },
    )

@login_required
def allTexts(request):
    """
    View for all text entries for logged in user
    """
    text_list = Text.objects.filter(user=request.user)

    paginator = Paginator(text_list, 10)
    page = request.GET.get('page')

    try:
        texts = paginator.page(page)
    except PageNotAnInteger:
        texts = paginator.page(1)
    except EmptyPage:
        texts = paginator.page(paginator.num_pages)
    
    return render(request, 'text-list.html', context={'texts':texts})

contentdensity/textifai/templates/account.html
{% extends "base.html" %}

{% block page_head %}
    <h1>Your Profile</h1>
{% endblock %}
<br>
{% block content %}
    <p>Welcome to your user page, <em>{{ user }}! </em></p>

    <div class="account-cards">
        <div class="card text-card">
            <div class="card-header">
                <h2> Recent Content </h2>
                <em> What have you written recently? </em>
                <a href="{% url 'text-list' %}" class="see-all">See All</a>
            </div>
            {% if texts %}
            {% for text in texts %}
            <div class="card-body">
                {% if text.title %}
                <a href="{% url 'featureoutput' pk=text.m_id %}">
                    <h3>{{ text.title }} <span class="author">{{ text.time_created }}</span></h3>
                </a>
                {% else %}
                <a href="{% url 'featureoutput' pk=text.m_id %}"><h3>{{ text.time_created }}</h3></a>
                {% endif %}
                <p>{{ text|truncatewords:40 }}</p>
            </div>
            {% endfor %}
            {% else %}
            <div class="card-body">
                <h3> Nothing yet. Why not try submitting something? </h3>
            </div>
            {% endif %}
        </div>
        
        <div class="card">
            <div class="card-header">
                <h2> Recent Comments </h2>
                <em> What have you been telling people lately? </em> 
            </div>
            {% if comments %}
            {% for comment in comments %}
            <div class="card-body">
                <a href="{% url 'featureoutput' pk=comment.text.m_id %}"><h3> {{ comment }} </h3></a>
                - On {{ comment.user }}'s text, "{{ comment.text|truncatewords:20 }}"
                <br>
                <em> {{ comment.time_created }} </em>
            </div>
            {% endfor %}
            {% else %}
            <div class="card-body">
                <h3> Nothing yet. Tell people what you think! </h3>
            </div>
            {% endif %}
        </div>
        
        <div class="card">
            <div class="card-header">
                <h2> Writing Analytics </h2>
                <em> Learn exciting facts about your writing! </em> 
            </div>
            {% if analytics %}
            {% for insight in analytics %}
            <div class="card-body">
                <h3> {{ insight.tone }} : <span class="prob">{{ insight.probability__avg|floatformat:-4 }}</span>%</h3>
            </div>
            {% endfor %}
            {% else %}
            <div class="card-body">
                <h3> Nothing yet. Why not try submitting something? </h3>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="administration">
        <h2>Administration</h2>
        <a href="{% url 'password_reset' %}">Reset Password</a>
    </div>

{% endblock %}

{% block inline_js %}
    <script>
    const probs = document.querySelectorAll('.prob');
    probs.forEach((prob) => {
        prob.innerText = (Number(prob.innerText) * 100).toFixed(2);
    })
    </script>
{% endblock %}

contentdensity/textifai/templates/base_2col.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center">
	<div class="col-9">
		{% block left_col %}{% endblock %}
	</div>
	<div class="col-3 genInsights">
		{% block right_col %}{% endblock %}
	</div>
</div>
{% endblock %}

contentdensity/textifai/templates/featureoutput.html
{% extends "base_2col.html" %} 
{% block page_head %}
<h1>Text Analysis</h1>
{% endblock %} 
{% block left_col %}
<div class="container">
    <br>
    <div class="card">
        <div class="card-header">
            {{ text.title }}
        </div>
        <div class="card-body">
            {{ text }}
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Insights</th>
                    <th>Probability</th>
                </tr>
            </thead>
            <tbody>
                {% for item in insights %}
                <tr>
                    <td>
                        {{ item.tone }}
                    </td>
                    <td>
                        {{ item.probability }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <form method="POST" action="">
        {% csrf_token %}
        <button type="submit" name="new_submission_button" value=True class="btn btn-primary">New Submission
        </button>
        {% if user.is_authenticated and user == author %}
        <button type="button" name="edit_text_button" data-toggle="modal" data-target="#editTextModal" class="btn btn-primary">Edit
        </button>
        {% endif %}
    </form>

</div>
<div class="container">
    <div class="modal fade" id="editTextModal" role="dialog">
        <div class="modal-dialog">
            <form id="edit_text_form_button" method="POST" action="">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Edit Submission</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <textarea class="form-control" style="resize: none;" id="id_edited_text" name="edited_text" rows="15">{{ text }}</textarea>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group">
                            {% csrf_token %}
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" name="edit_submission_button" value=True class="btn btn-primary">Save</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %} 
{% block right_col %}
<h5>Positivity
    <span class="badge badge-primary">{{ g_insights.positivity }}</span>
</h5>
<h5>Most Common Part of Speech
    <span class="badge badge-primary">{{ g_insights.most_common_pos }}</span>
</h5>
<h5>Reading Level
    <span class="badge badge-primary">{{ g_insights.reading_level }} </span>
</h5>
<h5>Reading Time
    <span class="badge badge-primary">{{ g_insights.reading_time }}</span>
</h5>
<h5>Speaking Time
    <span class="badge badge-primary">{{ g_insights.speaking_time }}</span>
</h5>
<h5>Total Sentences
    <span class="badge badge-primary">{{ g_insights.total_sentences }}</span>
</h5>
<h5>Total Words
    <span class="badge badge-primary">{{ g_insights.total_words }}</span>
</h5>
<h5>Total Characters
    <span class="badge badge-primary">{{ g_insights.total_chars }}</span>
</h5>
<h5>Most Common Word
    <span class="badge badge-primary">{{ g_insights.most_common_word }}</span>
</h5>
<h5>Average Word Length
    <span class="badge badge-primary">{{ g_insights.average_word_length }}</span>
</h5>
<h5>Word Reuse Percentage
    <span class="badge badge-primary">{{ g_insights.word_reuse_percentage }}</span>
</h5>
{% endblock %} 
{% block footer %}
<hr>
<br>
<div class="row justify-content-center">
    {% if user.is_authenticated %}
    <div class="row justify-content-center" style="width:100%;">
        <div class="container">
            <form method="POST" action="">
                <div class="form-group">
                    <label for="comment_input">Add Comment</label>
                    <textarea class="form-control" style="resize: none;" id="id_comment_input" name="comment_input" rows="2"></textarea>
                </div>
                <div class="form-group">
                    {% csrf_token %}
                    <button name="comment_input_button" type="submit" value=True class="btn btn-primary">Add Comment
                    </button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <h5>Login to add a comment</h5>
    {% endif %}
</div>
<br> 
{% for comment in comments %}
<div class="card">
    <div class="card-header">
        <strong>{{ comment.user.username }}</strong>
        <span class="text-muted">{{ comment.time_created }}</span>
    </div>
    <div class="card-body">
        {{ comment.content }}
    </div>
</div>
<br> 
{% endfor %} 
{% endblock %}

contentdensity/textifai/templates/general-insights.html
{% extends "base_2col.html" %}

{% block title %}
<title>Textifai - Global Insights</title>
{% endblock %}

{% block page_head %}
<h1>Global Insights</h1>
{% endblock %}

{% block left_col %}
<div class="row">
	{% for insight in insights %}
	<div class="col-3">
		<div class="insightCard">
			<span class="insightVal">{{ insight.value }}</span>
			<span class="insightLabel">{{ insight.name }}</span>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock %}

{% block right_col %}
<div class="row justify-content-center">
	<h3>Your contributions</h3>
</div>
{% if request.user.is_authenticated %}
{% for insight in personal_insights %}
<div class="insightCard">
	<span class="insightVal">{{ insight.1 }}</span>
	<span class="insightLabel">{{ insight.0 }}</span>
</div>
{% empty %}
<div class="row justify-content-center">
	<span><a href={% url 'textinput' %}>Add something</a> to contribute!</span>
</div>
{% endfor %}
{% else %}
<div class="row justify-content-center">
	<span><a href="{% url 'login' %}" class="log">Log in</a> to see your contributions</span>
</div>
{% endif %}
</div>
{% endblock %}

contentdensity/textifai/templates/index.html
{% extends "base.html" %}

{% block page_head %}
<h1>Textifai</h1>
<form method="POST" action="" class="search">
	{% csrf_token %}		
	<input name="search_input" id="id_search_input" type="search" placeholder="Search"><input type="submit" value=" ">
</form>
{% endblock %}

<!-- Recent Posts -->
{% block content %}
<h2>Recent Posts</h2>
{% for entry in recent %}
	<div class="insightCard recents">
		{% if entry.title %}
			<h3>{{ entry.title }} <span class="author">By: {{ entry.user }}</span></h3>
		{% else %}
			<h3>{{ entry.time_created }} <span class="author">By: {{ entry.user }}</span></h3>
		{% endif %}
		<p class="content">{{ entry.content }}</p>
		<a href="{% url 'featureoutput' pk=entry.m_id %}">View Text</a>
	</div>
{% endfor %}
{% endblock %}

<!-- Scripts -->
{% block inline_js %}
<script>
	let content = document.querySelectorAll('.content');
	content.forEach((i) => {
		if (i.innerText.length > 500) i.innerText = i.innerText.substring(0, 400) + '...';
	});
</script>
{% endblock %}

contentdensity/textifai/templates/searchresults.html
{% extends "base.html" %}

{% block page_head %}
<h1>Textifai</h1>
<form method="POST" action="" class="search">
	{% csrf_token %}		
	<input name="search_input" id="id_search_input" type="search" placeholder="Search"><input type="submit" value=" ">
</form>
{% endblock %}

{% block content %}
<h2>Search Results</h2>
{% if results %}
	{% for entry in results %}
		<div class="insightCard recents">
			{% if entry.title %}
				<h3>{{ entry.title }} <span class="author">By: {{ entry.user }}</span></h3>
			{% else %}
				<h3>{{ entry.time_created }} <span class="author">By: {{ entry.user }}</span></h3>
			{% endif %}
			<p class="content">{{ entry.content }}</p>
			<a href="{% url 'featureoutput' pk=entry.m_id %}">View Text</a>
		</div>
	{% endfor %}
{% else %} 
	<p>No results found.</p>
{% endif %}
{% endblock %}

<!-- Scripts -->
{% block inline_js %}
<script>
	let content = document.querySelectorAll('.content');
	content.forEach((i) => {
		if (i.innerText.length > 500) i.innerText = i.innerText.substring(0, 400) + '...';
	});
</script>
{% endblock %}

contentdensity/textifai/templates/textinput.html
{% extends "base.html" %} 
{% block title %}
<title>Textifai - Text Analysis Input</title>
{% endblock %} 
{% block page_head %}
<h1>Text Analysis Input</h1>
{% endblock %} 
{% block content %}
<p>Not sure what to write? Try Textifai with one of the samples from the dropdown menu below. </p> 
<div class="dropdown">
    <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sample text
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <a class="dropdown-item" value="The media has been speculating that I fired Rex Tillerson or that he would be leaving soon - FAKE NEWS! He’s not leaving and while we disagree on certain subjects, (I call the final shots) we work well together and America is highly respected again!" 
      id="trump" onclick="sendTextToForm()">Donald Trump</a>
    </div>
</div>
<br> 
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_text_title">Enter Title</label>
        <input type="text" id="id_text_title" name="text_title" class="form-control">
        <label for="text_analysis_input">Enter text</label>
        <textarea class="form-control" style="resize: none;"
                    id="id_text_analysis_input"
                    name="text_analysis_input" rows="15"></textarea>
    </div>
    <div class="form-group">
        {% comment %} 
        <label for="uploadTextFile">Upload text</label>
        <input type="file" class="form-control-file" id="uploadTextFile" aria-describedby="fileHelp">
        <small id="fileHelp" class="form-text text-muted">Accepted formats: [formats to be determined]
        </small> 
        {% endcomment %}
        <button type="submit" class="btn btn-primary">Analyze
        </button>
    </div>
</form>
<script> 
    function sendTextToForm() { 
        inputDiv = document.getElementById("id_text_analysis_input");
        var text = document.getElementById("trump").getAttribute('value'); 
        inputDiv.value = text;
        
        titleDiv = document.getElementById("id_text_title");
        titleDiv.value = "Donald Trump Tweet"
    }
</script> 
{% endblock %}